### ISSUE TITLE
Version 3.0.11 breaks build

### ISSUE THREAD

**Issue by kmort89** [spring-projects/spring-ws#1224]
Hi,
we're getting lots of unresolved import errors with version 3.0.11 that don't exist with 3.0.10

```
error: package org.springframework.ws.client.core.support does not exist
import org.springframework.ws.client.core.support.WebServiceGatewaySupport;

error: package org.springframework.ws.client.support.interceptor does not exist
import org.springframework.ws.client.support.interceptor.ClientInterceptor;
                                                        ^
 error: package org.springframework.ws.soap.client does not exist
import org.springframework.ws.soap.client.SoapFaultClientException;
                                         ^
error: package org.springframework.ws.soap.client.core does not exist
import org.springframework.ws.soap.client.core.SoapActionCallback;
                                              ^

```

Project builds fine with "3.0.10.RELEASE" but since yesterday "3.0.+" broke the build.
Might be related to our spring-integration-ws lock "org.springframework.integration:spring-integration-ws:5.3.+".

**Comment by kmort89** [comment]
Additional info, the actual artifacts that I'm referring to:
```
"org.springframework.ws:spring-ws-support:3.0.11.RELEASE"
"org.springframework.ws:spring-ws-core:3.0.11.RELEASE"
```
Replace .11 with .10 and the build works.

**Comment by gregturn** [comment]
Confirmed. Looks like a particular patch wasn't backported to the `3.x` branch.

**Comment by gregturn** [comment]
Looks like https://github.com/spring-projects/spring-ws/commit/72552397d5adc861e9d265ec2088637021009736 was the missing patch.

**Comment by gregturn** [comment]
Resolved via 2855ca43.

**Comment by gregturn** [comment]
3.0.12.RELEASE is on maven central. Check it out @kmort89!

**Comment by kmort89** [comment]
@gregturn thank you, I've just confirmed that 3.0.12.RELEASE fixes our case as well. :+1:
