### ISSUE TITLE
NoSuchMethodError when using Axiom 1.2.14 [SWS-930]

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-ws#1004]
**[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson)** opened **[SWS-930](https://jira.spring.io/browse/SWS-930?redirect=false)** and commented

The changes made for #995 have resulted in Spring Web Services no longer working with Axiom 1.2.14. Specifically the move to using `getSOAPMessage` in place of the, deprecated in 1.2.15, `getSoapMessage`. IMO, it would be preferable to continue to use `getSoapMessage` and suppress the deprecation warning. This approach will make things compatible with Axiom 1.2.14 _and_ 1.2.15.

---

**Affects:** 2.2.4

**Referenced from:** commits https://github.com/spring-projects/spring-ws/commit/4cbc75c060239616a34a996d69f258be4ac978f5
